on: [push, pull_request]

jobs:
  test:
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    strategy:
      matrix:
        ros_distro: [noetic]
        ubuntu_distro: [focal]
        arch: [amd64]
    steps:
      - uses: ros-tooling/setup-ros@v0.4
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: nmea_navsat_driver
          target-ros1-distro: ${{ matrix.ros_distro }}
